############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Research"
url = "research/"
weight = 2

[[main]]
name = "Publications"
url = "publications/"
weight = 3

[[main]]
name = "Outreach"
url = "Outreach/"
weight = 4

[[main]]
weight = 5
name = "More"
hasChildren = true

  [[main]]
  parent = "More"
  name = "Communications"
  url = "communications/"
  weight = 1
  
  [[main]]
  parent = "More"
  name = "Teaching"
  url = "teaching/"
  weight = 2
  
[[main]]
name = "Contact"
url = "contact/"
weight = 6


# footer menu
[[footer]]
name = "Research"
url = "research/"
weight = 2

[[footer]]
name = "Publications"
url = "publications/"
weight = 3

[[footer]]
name = "Outreach"
url = "Outreach/"
weight = 4

[[footer]]
name = "Contact"
url = "contact/"
weight = 5
