############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Publications"
url = "publications/"
weight = 3

[[main]]
name = "Outreach"
url = "Outreach/"
weight = 4

[[main]]
weight = 5
name = "More"
hasChildren = true

  [[main]]
  parent = "More"
  name = "Blog"
  url = "Blog/"
  weight = 1

  [[main]]
  parent = "More"
  name = "Conferences"
  url = "conferences/"
  weight = 2

  [[main]]
  parent = "More"
  name = "FAQ"
  url = "faq/"
  weight = 3
  
[[main]]
name = "Contact"
url = "contact/"
weight = 6


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Project"
url = "project/"
weight = 3

[[footer]]
name = "Service"
url = "service/"
weight = 4

[[footer]]
name = "Pricing"
url = "pricing/"
weight = 5

[[footer]]
name = "FAQ"
url = "faq/"
weight = 6

[[footer]]
name = "Contact"
url = "contact/"
weight = 7
